### PR TITLE
Wildcard method signatures

### PR DESCRIPTION
**Pull request by madrob**
Allow specifying all methods regardless of argument types, for example:

List.of(**) would match all of the factory methods. This is useful when you want to match those methods without listing them individually and also not forbidding the entire class.

I did not see unit tests for this class, so I wasn't sure where to add testing.

### CODE REVIEW

**Comment by uschindler** [comment]
Hi Mike,

thanks for this PR! Looks like a good thing. I have the feeling that there was already an issue about this! What I really like is that it will trigger a method not found issue if you add a false signature like `some.ClazzThatExists#methodWithTypo(**)` (not matching any method).

I'd like to make some antunit test for this before merging it in -- to be sure That should be easy. I am a bit busy today with log4j, but will check out for sure.

Uwe

**Comment by uschindler** [comment]
Of course an update for the documentation is required.

**Comment by uschindler** [comment]
Hi @madrob, 
I rewrote the parser a bit to get rid of the "ignoreMethodArgs" boolean. It is also lenient to whitespace like ASM's parser.

I also added a few tests.

Next I will update documentation, but code-wise it's ready.

**Comment by uschindler** [comment]
It's now ready. Just give me your go, @madrob. Does this fit your needs?

**Comment by madrob** [comment]
That looks pretty cool from initial code review. I think it should be good to merge, but I won’t get a chance to test this until next week.

**Comment by uschindler** [comment]
OK, will merge. Are you planning to use this in Solr/Lucene or for own projects?

I am not yet sure if those 2 changes I merged today should be a new release, or if I should wait for Java 18.

**Comment by madrob** [comment]
My current plan was to use it for Solr.

**Comment by uschindler** [comment]
Give me a ping if you need it urgently, then I will do a release.

As usual before release there need to be some checks:
- Check for new commons-io versions and analyze them
- Check ASM version bugfixes

**Comment by madrob** [comment]
I’m on vacation until January, so no rush at all.

would you be interested in adding some commons io signatures to the default list? Specifically, I’m looking at IOUtils.copy since they can be replaced by jdk native methods

**Comment by uschindler** [comment]
> would you be interested in adding some commons io signatures to the default list? Specifically, I’m looking at IOUtils.copy since they can be replaced by jdk native methods

I would only add real unsafe commons-io methods. The copy methods are fine, just unneeded with newer JDKs. We may ship in future with other "recommended replacements" signatures. Like forbid `java.io.File` (see Lucene) and refer to `java.nio.file.Path`.

**Pull request merged**
