### PR TITLE
A typo in the resource name

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by uschindler** [comment]
Thanks Dawid, will merge that :-)

**Comment by dweiss** [comment]
You're welcome :)

**Comment by uschindler** [comment]
Lol I think the file name was correct :-)

It was meant as includes/excludes. Has nothing to do with index. But in any case: will use better file name

**Comment by uschindler** [comment]
Renamed it in 13a6b3f9cf4d65aa5accd3e8357fe9271a9ef156

**Comment by dweiss** [comment]
Oh man... sorry. My in-memory spell checker has a very high priority for typos on 'index'...

**Comment by uschindler** [comment]
Same here. Looked like a typo :-)

**Pull request merged**
